# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gfs.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'gfs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tgfs.proto\x12\x03GFS\"\x0e\n\x0c\x45mptyRequest\"\x1f\n\nIDResponse\x12\x11\n\tclient_id\x18\x01 \x01(\x05\"\x18\n\x06String\x12\x0e\n\x06string\x18\x01 \x01(\t\"\'\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\xff\x02\n\x0eMasterToClient\x12.\n\x06get_id\x12\x11.GFS.EmptyRequest\x1a\x0f.GFS.IDResponse\"\x00\x12)\n\x0b\x63reate_file\x12\x0b.GFS.String\x1a\x0b.GFS.Status\"\x00\x12)\n\x0b\x64\x65lete_file\x12\x0b.GFS.String\x1a\x0b.GFS.Status\"\x00\x12*\n\nlist_files\x12\x0b.GFS.String\x1a\x0b.GFS.String\"\x00\x30\x01\x12,\n\x0eget_chunk_locs\x12\x0b.GFS.String\x1a\x0b.GFS.Status\"\x00\x12*\n\x0c\x63ommit_chunk\x12\x0b.GFS.String\x1a\x0b.GFS.Status\"\x00\x12\x30\n\x12\x66ile_create_status\x12\x0b.GFS.String\x1a\x0b.GFS.Status\"\x00\x12/\n\x11get_chunk_details\x12\x0b.GFS.String\x1a\x0b.GFS.Status\"\x00\x32i\n\rChunkToClient\x12,\n\x0c\x63reate_chunk\x12\x0b.GFS.String\x1a\x0b.GFS.Status\"\x00(\x01\x12*\n\nread_chunk\x12\x0b.GFS.String\x1a\x0b.GFS.String\"\x00\x30\x01\x32o\n\x0c\x43hunkToChunk\x12,\n\x0c\x63reate_chunk\x12\x0b.GFS.String\x1a\x0b.GFS.Status\"\x00(\x01\x12\x31\n\x11read_entire_chunk\x12\x0b.GFS.String\x1a\x0b.GFS.String\"\x00\x30\x01\x32\xc2\x01\n\rChunkToMaster\x12*\n\x0c\x63ommit_chunk\x12\x0b.GFS.String\x1a\x0b.GFS.Status\"\x00\x12-\n\rdelete_chunks\x12\x0b.GFS.String\x1a\x0b.GFS.Status\"\x00(\x01\x12-\n\x0freplicate_chunk\x12\x0b.GFS.String\x1a\x0b.GFS.Status\"\x00\x12\'\n\theartbeat\x12\x0b.GFS.String\x1a\x0b.GFS.Status\"\x00\x32?\n\rMasterToChunk\x12.\n\x0cquery_chunks\x12\x0b.GFS.String\x1a\x0b.GFS.String\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gfs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYREQUEST']._serialized_start=18
  _globals['_EMPTYREQUEST']._serialized_end=32
  _globals['_IDRESPONSE']._serialized_start=34
  _globals['_IDRESPONSE']._serialized_end=65
  _globals['_STRING']._serialized_start=67
  _globals['_STRING']._serialized_end=91
  _globals['_STATUS']._serialized_start=93
  _globals['_STATUS']._serialized_end=132
  _globals['_MASTERTOCLIENT']._serialized_start=135
  _globals['_MASTERTOCLIENT']._serialized_end=518
  _globals['_CHUNKTOCLIENT']._serialized_start=520
  _globals['_CHUNKTOCLIENT']._serialized_end=625
  _globals['_CHUNKTOCHUNK']._serialized_start=627
  _globals['_CHUNKTOCHUNK']._serialized_end=738
  _globals['_CHUNKTOMASTER']._serialized_start=741
  _globals['_CHUNKTOMASTER']._serialized_end=935
  _globals['_MASTERTOCHUNK']._serialized_start=937
  _globals['_MASTERTOCHUNK']._serialized_end=1000
# @@protoc_insertion_point(module_scope)
